tasks:
  - init: |
      docker compose pull
  - command: |
      docker compose up -d
      pip install -r requirements.txt

ports:
  - port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter
    - almenon.arepl
    - hbenl.vscode-test-explorer
    - ms-python.python